name: CI Pipeline

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print Hello
              run: echo "Hello, World!"

            - name: Run npm install
              working-directory: ./frontend
              run: npm install

            - name: Run npm run build
              working-directory: ./frontend
              run: npm run build

            - name: Building Docker Image
              working-directory: ./frontend
              run: docker build -t frontend .
